#!/usr/bin/env python3
# syntax_check.py <source-file>
#
# Runs a full compiler syntax+semantic check on a single source file without
# producing any output (.o) file.  This gives richer diagnostics than
# `clangd --check`, because the compiler emits all "note:" lines too —
# including "unimplemented pure virtual method 'runOnOperation'" when a
# required override is missing.
#
# How it works:
#   1. Read build-ninja/compile_commands.json to find the exact compiler
#      invocation that CMake uses for the given file.  This ensures we use
#      exactly the same include paths, defines, and flags as the real build.
#   2. Replace the "-c" flag (compile to object file) with "-fsyntax-only"
#      (parse and typecheck only, write nothing to disk).
#   3. Strip the "-o <output>" argument, which is meaningless with -fsyntax-only.
#   4. Run the modified command in the same working directory that CMake used,
#      so relative paths inside the command resolve correctly.

import json, re, subprocess, sys

# The source file to check is passed as the first argument (${file} in tasks.json).
file = sys.argv[1]

# Load the compilation database generated by CMake.
db = json.load(open("/home/yeyang/mlir-tutorial/build-ninja/compile_commands.json"))

# Find the entry whose "file" field matches the source file we want to check.
entry = next(e for e in db if e["file"] == file)

# Start with the raw compile command string (e.g. "/usr/bin/c++ -DGTEST... -c foo.cpp").
cmd = entry["command"]

# Swap "-c" (compile to .o) for "-fsyntax-only" (check only, no output).
cmd = cmd.replace(" -c ", " -fsyntax-only ")

# Remove "-o <path>" since there is no output file when using -fsyntax-only.
cmd = re.sub(r"-o\s+\S+", "", cmd)

# Run the command.  shell=True lets us pass the whole string at once.
# cwd matches the directory CMake used so relative paths work.
subprocess.run(cmd, shell=True, cwd=entry["directory"])
